version: '3'

services:
  tts-backend:
    image: my-tts-api # development image
    #image: ghcr.io/lzieniew/tortoise-tts-api:main # deployment image
    ports:
      - "5000:5000"
    volumes:
        - ./results:/src/results
        - ./cache/:/root/.cache/
    deploy:
        resources:
            reservations:
                devices:
                  - driver: nvidia
                    device_ids: ['0']
                    capabilities: [gpu]
  
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./static:/static
