version: '3'

services:
  tts-backend:
    image: your_tts_image
    ports:
      - "5000:5000"
  
  web-frontend:
    image: your_web_frontend_image
    ports:
      - "8080:8080"
  
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
