version: '3'

services:
  tts-backend:
    image: ghcr.io/lzieniew/tortoise-tts-api:latest
    ports:
      - "5000:5000"
  
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
